name: Build Android Apk

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering if needed

permissions: # <--- ADDED THIS GLOBAL PERMISSIONS BLOCK
  contents: write # Grants permission to create and edit repository content (needed for releases)

jobs:
  spell-check:
    timeout-minutes: 5
    name: Check spelling
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v4

      - name: Check spelling
        uses: crate-ci/typos@master
        with:
          config: ./_typos.toml

  quality:
    timeout-minutes: 5
    name: Linting and formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Biome
        uses: biomejs/setup-biome@v2

      - name: Run Biome
        run: biome ci .

  build-android-apk:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Apache Cordova CLI
        run: npm install -g cordova

      - name: Set up Java Development Kit (JDK)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          # This is required because the Android SDK's sdkmanager tool
          # is compiled with Java 17 (class file version 61.0).

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: '33'
          build-tools: '33.0.0' # Ensure this matches the version used for apksigner

      - name: Initial setup (yarn setup)
        run: yarn setup

      - name: Build Android Release AAB
        run: yarn build android free prod

      - name: Locate AAB artifact
        id: locate_aab
        run: |
          AAB_PATH=$(find . -name "app-release.aab" | head -n 1)
          if [ -z "$AAB_PATH" ]; then
            echo "Error: No release AAB found after build! Check previous steps' logs for build failures."
            ls -R .
            exit 1
          fi
          echo "Found AAB at: $AAB_PATH"
          echo "AAB_PATH=$AAB_PATH" >> "$GITHUB_OUTPUT"

      - name: Install Bundletool
        run: |
          # Use a specific version for reliability. Check https://github.com/google/bundletool/releases for the latest stable.
          wget https://github.com/google/bundletool/releases/download/1.16.0/bundletool-all-1.16.0.jar -O bundletool.jar
          echo "BUNDLETOOL_JAR=$GITHUB_WORKSPACE/bundletool.jar" >> "$GITHUB_ENV"

      - name: Generate APK from AAB
        id: generate_apk_from_aab # This ID is necessary for outputting the path
        run: |
          AAB_PATH="${{ steps.locate_aab.outputs.AAB_PATH }}"
          OUTPUT_APKS_PATH="app-release.apks"

          java -jar "${{ env.BUNDLETOOL_JAR }}" build-apks \
            --bundle="$AAB_PATH" \
            --output="$OUTPUT_APKS_PATH" \
            --mode=universal

          unzip "$OUTPUT_APKS_PATH" -d apks_output

          UNIVERSAL_APK_PATH=$(find apks_output -name "universal.apk" | head -n 1)

          if [ -z "$UNIVERSAL_APK_PATH" ]; then
            echo "Error: Universal APK not found after bundletool conversion!"
            ls -R apks_output
            exit 1
          fi
          echo "Found universal APK at: $UNIVERSAL_APK_PATH"
          echo "APK_GENERATED_PATH=$UNIVERSAL_APK_PATH" >> "$GITHUB_OUTPUT"

      # --- FIXED STEP: Sign the Universal APK with Debug Key ---
      - name: Sign Universal APK with Debug Key
        run: |
          APK_TO_SIGN="${{ steps.generate_apk_from_aab.outputs.APK_GENERATED_PATH }}"
          
          # Directly use the known build-tools version from your setup-android action
          BUILD_TOOLS_VERSION='33.0.0' # <--- FIXED THIS LINE
          APKSIGNER="$ANDROID_HOME/build-tools/$BUILD_TOOLS_VERSION/apksigner"

          if [ ! -f "$APKSIGNER" ]; then
            echo "Error: apksigner not found at $APKSIGNER. Please check Android SDK setup."
            exit 1
          fi

          echo "Signing $APK_TO_SIGN using debug key..."
          "$APKSIGNER" sign \
            --ks ~/.android/debug.keystore \
            --ks-key-alias androiddebugkey \
            --ks-pass pass:android \
            "$APK_TO_SIGN"

          # Optional: Verify the APK signature for debugging purposes
          echo "Verifying APK signature..."
          "$APKSIGNER" verify "$APK_TO_SIGN"
          echo "APK signing complete."

      - name: Upload APK artifact # This is your existing artifact upload, which is still good for temporary access
        uses: actions/upload-artifact@v4
        with:
          name: android-release-apk
          path: ${{ steps.generate_apk_from_aab.outputs.APK_GENERATED_PATH }} # This path now points to the signed APK
          retention-days: 7

  # --- JOB TO CREATE A GITHUB RELEASE ---
  create-release:
    name: Create GitHub Release
    needs: build-android-apk # This job depends on the APK build succeeding
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Only create a release when pushing to 'main' branch

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js for release job # <--- Added this to ensure 'node' command is available
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Get project name and version # <--- This step relies on Node.js to read package.json
        id: project_info
        run: |
          PROJECT_NAME=$(basename "${{ github.repository }}")
          VERSION=$(node -p "require('./package.json').version")

          echo "PROJECT_NAME=$PROJECT_NAME" >> "$GITHUB_OUTPUT"
          echo "APP_VERSION=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Download APK artifact # Download the APK produced by the previous job
        uses: actions/download-artifact@v4
        with:
          name: android-release-apk # Match the name from the upload step
          path: ./release_artifacts # Download to a specific folder

      - name: Rename APK and prepare for upload # <--- This step renames the APK with project name and version
        id: prepare_apk
        run: |
          PROJECT_NAME="${{ steps.project_info.outputs.PROJECT_NAME }}"
          APP_VERSION="${{ steps.project_info.outputs.APP_VERSION }}"
          OLD_APK_PATH="./release_artifacts/universal.apk"
          NEW_APK_NAME="${PROJECT_NAME}-v${APP_VERSION}.apk"
          NEW_APK_PATH="./release_artifacts/${NEW_APK_NAME}"

          mv "$OLD_APK_PATH" "$NEW_APK_PATH"
          echo "New APK path: $NEW_APK_PATH"
          echo "RELEASE_APK_PATH=$NEW_APK_PATH" >> "$GITHUB_OUTPUT"
          echo "RELEASE_APK_NAME=$NEW_APK_NAME" >> "$GITHUB_OUTPUT"

      - name: Create Release and Upload APK
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ steps.project_info.outputs.APP_VERSION }}" # Tag based on package.json version
          name: "${{ steps.project_info.outputs.PROJECT_NAME }} Release v${{ steps.project_info.outputs.APP_VERSION }}"
          body: |
            New Android APK for version ${{ steps.project_info.outputs.APP_VERSION }}.
            Automatic release from GitHub Actions.
          draft: false # Set to true to create a draft release you can edit later
          prerelease: false # Set to true for pre-release versions
          files: ${{ steps.prepare_apk.outputs.RELEASE_APK_PATH }} # Path to the renamed, signed APK
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is automatically available
