      - name: Set up Java Development Kit (JDK)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17' # This was set to 17, which is correct for sdkmanager
          # This is required because the Android SDK's sdkmanager tool
          # is compiled with Java 17 (class file version 61.0).

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: '33' # Adjust if needed
          build-tools: '33.0.0' # Adjust if needed
