      - name: Install Android SDK Build Tools and Platforms
        run: |
          # Define Android SDK Root - this is where all SDK components will be installed
          ANDROID_SDK_ROOT="${{ runner.temp }}/android-sdk"
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV # Make this available for subsequent steps

          mkdir -p "$ANDROID_SDK_ROOT"

          # Download and unzip the Android command-line tools
          # The zip usually contains a 'cmdline-tools' directory.
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-8583971_latest.zip -O cmdline-tools.zip
          unzip -q cmdline-tools.zip

          # Move the extracted 'cmdline-tools' contents into the desired 'latest' directory
          # This ensures sdkmanager is at $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools/latest"
          mv cmdline-tools/* "$ANDROID_SDK_ROOT/cmdline-tools/latest/"

          # Add the 'bin' directory of the command-line tools to the system's PATH
          # This is crucial so that 'sdkmanager' can be found and executed
          echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH
          
          # Accept Android SDK licenses (essential for sdkmanager to function)
          yes | sdkmanager --licenses > /dev/null

          # Install specific Android SDK components needed for the build
          # Based on your previous setup (API level 33, build tools 33.0.0)
          sdkmanager "platform-tools" "build-tools;33.0.0" "platforms;android-33"
